### ISSUE TITLE
Filter by username doens't work

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#12]
Affects: logevents.php
The filter by username filter doesn't work.

**Comment by caeze** [comment]
Fixed in 588c37b17bbd9989041654b7692108245040898c.

**Comment by caeze** [comment]
The issue was that usernames were written with parentheses in the database. So old log events are still affected, but new ones will not be.

**Comment by caeze** [comment]
Fixed in 588c37b.
