### ISSUE TITLE
Missing Texts

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/ppi#13]
Internationalizations for both 🇩🇪 and 🇬🇧 required!
---
All internationalization Strings are found in [`core/i18n/de.txt`](https://github.com/fsi-tue/ppi/blob/main/core/i18n/de.txt) and [`core/i18n/en.txt`](https://github.com/fsi-tue/ppi/blob/main/core/i18n/en.txt)

Currently empty or sparce fields regard:
* FAQ/help texts  (`...Help...=...`)
* Replies for accepted/denied protocols (`uploadReply[1->9]=...`)

If a Field is filled with content please change for **both** languages.

### How to
Each line contains the complete content String. Valid String are written in HTML.
Hence a Linebreak is `<br>`

**Comment by caeze** [comment]
Replies for accepted/denied protocols (uploadReply[1->9]=...) is enhanced in 264d73552c4857f11d61cc62e2e9455e43a09d6f and 45b84948a910c2d54b20ddd5e081ae5c5e39f964.

**Comment by caeze** [comment]
No one has complained about any misleading or not verbose enough texts. Closing this now. If anyone wants to make improvements in the core/i18n/de.txt and core/i18n/en.txt localization files, please do so.
