### ISSUE TITLE
Merge same lectures with different names and rename some other

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#14]
There are several lectures with different names which are actually the same. These should be merged.
Some lectures should be renamed to a consistent naming scheme.
### Mathe 1
- Mathe-1
- Mathematik für Informatiker I

### Mathe 2
- Mathe-2
- Mathe 2 für Informatiker

### Mathe 3
- Mathe-3
- Mathe 3 für (Bio-)Informatiker

### Medizinische Bildverarbeitung
- rename to Medizinische Visualisierung

### Informatik I / II / III
- rename to Informatik 1 / 2 / 3

**Comment by caeze** [comment]
I suggest to download all the protocols of these lectures. Then delete all these lectures and re-upload. Is a bit of work, but probably the most stable solution.

**Comment by not-a-feature** [comment]
Merging has been done.
Renaming still to do.

**Comment by not-a-feature** [comment]
Done
