### ISSUE TITLE
Path of new protocols isn't updated, resulting in error

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#15]
After accepting an uploaded protocol, the path isn't updated or is wrongly updated. This is resulting in an error.
The new protocol can't be added to the zip.

Example: Can not add file to zip archive! File to add not found: /var/www/html/exam_protocols/protocols//var/www/html/exam_protocols/protocols/95df29c7d7686df84dddc162a8408998d36286f2553e92ec066ac2266c9f47b4.pdf!

The old path "/var/www/html/exam_protocols/protocols/95df29c7d7686df84dddc162a8408998d36286f2553e92ec066ac2266c9f47b4.pdff" should be updated to "95df29c7d7686df84dddc162a8408998d36286f2553e92ec066ac2266c9f47b4"

**Comment by luoe** [comment]
I think it is already wrongly uploaded and inserted into the database. The path shouldn't be changed if not explicitly set/changed.
 This can be seen [here](https://github.com/fsi-tue/ppi/blob/c04f11fbd976d0a7cb9cdaddb3c4787882e72bed/core/system_classes/ExamProtocolSystem.php#L76). The path will be prepended already when downloading/accessing the file.
