### ISSUE TITLE
Registration email does not reach the user.

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#16]
Two users tried to register a new account. Both used their correct (zx-) account names but did not receive an email. 

In order to prevent this, a better email sending system should be implemented. Preferably over smtp via the student union mail-server.

**Comment by caeze** [comment]
Users should be able to re-register when it did not work the first time. The registration mail shall be re-sent when users try to re-register an already registered user.

**Comment by caeze** [comment]
Fixed in e85436fac7d1303ba1a36a32c437ca12a149bb0a.
