### ISSUE TITLE
Expired download links aren't removed

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#19]
The download link expires after 3 weeks. After that, the user should be able to buy the same lecture a second time. This is currently not possible as the lecture.php is showing that the user already bought the lecture while the download.php

**lecture.php** 
![grafik](https://user-images.githubusercontent.com/25013642/107150603-cd787d00-695e-11eb-871b-2c91937ad3b3.png)

**download.php**
![grafik](https://user-images.githubusercontent.com/25013642/107150569-aae66400-695e-11eb-8fa2-0899205836b0.png)

**Comment by caeze** [comment]
Fixed in 9f32b75e919dcf633058cf2cec21b3661e86cdcb. Will create PR.
