### ISSUE TITLE
More accept/deny reasons

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#2]
When an admin rejects or accepts an exam, there is only one default reason.

**Comment by not-a-feature** [comment]
Closed with #17

**Comment by luoe** [comment]
@not-a-feature See [this](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for autoclosing issues with a commit message in a PR. (e.g. when merging, "`Fix #2`"
