### ISSUE TITLE
Change $filePath to $fileName in all remaining files

### ISSUE THREAD

**Issue by luoe** [fsi-tue/ppi#20]
This change was introduced in #18, now the naming in other files, especially core/data_classes/ExamProtocol.php need to be changed, too.

**Comment by caeze** [comment]
Fixed in aa53d62, will create PR at some point

**Comment by caeze** [comment]
Important: the database column name has changed from filePath to fileName to reflect this change! This needs to be changed on the system as well!
So from now on, we are only storing file names in the DB, the path is prepended when accessing files.
Also, the DB needs to be cleaned to not contain any paths before filenames.

**Comment by caeze** [comment]
DB cleaning can be done with:



UPDATE
   "public"."ExamProtocols"
SET
  "fileName" = regexp_replace(
    "fileName", '(.*\/)', '', 'g'
  )

**Comment by caeze** [comment]
Fixed in aa53d62.

**Comment by luoe** [comment]
Thanks @caeze  :)
