### ISSUE TITLE
Admin Protocoll View: show lecture

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/ppi#32]
It would be nice to see what lecture a new upload belongs to. 

That makes it easier to recognise which lecture has a current protocol already accepted.

**Comment by not-a-feature** [comment]
![grafik](https://user-images.githubusercontent.com/25013642/121771884-6a982c00-cb72-11eb-8fc1-ec83475525eb.png)
 This should make it easier

**Comment by caeze** [comment]
Also added info about lecture of protocol in the list.
