### ISSUE TITLE
Bug: CRITICAL Attempt to download off-directory file 

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#5]
Step to reproduce:

- Admin Pane:l List of Protocols
- Change Lecture of protocol
- Try to download protocol
- --> Empty white page (examprotocolslist.php?download=582)

![bug](https://user-images.githubusercontent.com/25013642/104001550-1e4e5780-51a0-11eb-9b3f-b57becf10df6.png)

**Comment by not-a-feature** [comment]
Apparently, this occurs also with very protocol merged from V1. Newly uploaded protocols aren't affected.

![grafik](https://user-images.githubusercontent.com/25013642/104014361-2fed2a80-51b3-11eb-9d66-c2cb81dd2285.png)

The download as zip-file is not affected.

**Comment by luoe** [comment]
You forgot to blacken your username :P

**Comment by caeze** [comment]
Fixed by issue #20.

**Comment by luoe** [comment]
Thanks :)
