### ISSUE TITLE
Admin Panel: Sort lecture selection dropdown alphabetically. 

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/ppi#6]
Affects file: /viewexamprotocol.php

In the detailed view of a protocol, the lectures of the "Assigned to Lectures" selection menu aren't sorted alphabetically.
One could use the same function as in `upload.php` or extract this function into a dao/system class.

**Comment by caeze** [comment]
Fixed in db0a2e95ceb4487853eb6943ea035ca993a5796c and removed side effects (better fix) in 55ca68854b2ca604205b8f7027b85a7950f7adee.
